import { NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { generateShortId, generateSlug } from '@/lib/utils'

const sampleCars = [
  {
    title: 'BMW 330i M Sport',
    brand: 'BMW',
    model: '330i',
    year: 2021,
    price: 42500,
    mileage: 35000,
    fuelType: 'petrol',
    transmission: 'automatic',
    bodyType: 'sedan',
    condition: 'used',
    colorExterior: 'Alpine White',
    colorInterior: 'Black',
    powerHP: 258,
    engine: '2.0L Turbo',
    drivetrain: 'rwd',
    seats: 5,
    doors: 4,
    features: ['M Sport Package', 'LED Headlights', 'Navigation', 'Heated Seats', 'Parking Sensors'],
    description: 'Beautiful BMW 330i with M Sport package. Full service history, one owner. Excellent condition inside and out.',
    images: ['https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80', 'https://images.unsplash.com/photo-1520050206757-67e75163f484?w=800&q=80'],
    isFeatured: true,
    status: 'available',
  },
  {
    title: 'Mercedes-Benz C200 AMG Line',
    brand: 'Mercedes-Benz',
    model: 'C200',
    year: 2022,
    price: 48900,
    mileage: 22000,
    fuelType: 'petrol',
    transmission: 'automatic',
    bodyType: 'sedan',
    condition: 'used',
    colorExterior: 'Obsidian Black',
    colorInterior: 'Beige',
    powerHP: 204,
    engine: '1.5L Turbo',
    drivetrain: 'rwd',
    seats: 5,
    doors: 4,
    features: ['AMG Line', 'Panoramic Roof', 'Burmester Sound', 'Ambient Lighting', '360 Camera'],
    description: 'Stunning Mercedes C200 with AMG Line styling. Premium interior with all the latest technology.',
    images: ['https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&q=80', 'https://images.unsplash.com/photo-1606611013016-969c19ba27bb?w=800&q=80'],
    isFeatured: true,
    status: 'available',
  },
  {
    title: 'Audi A4 Avant S-Line',
    brand: 'Audi',
    model: 'A4 Avant',
    year: 2020,
    price: 38500,
    mileage: 48000,
    fuelType: 'diesel',
    transmission: 'automatic',
    bodyType: 'wagon',
    condition: 'used',
    colorExterior: 'Glacier White',
    colorInterior: 'Black',
    powerHP: 190,
    engine: '2.0 TDI',
    drivetrain: 'awd',
    seats: 5,
    doors: 5,
    features: ['S-Line', 'Virtual Cockpit', 'Matrix LED', 'Bang & Olufsen', 'Adaptive Cruise'],
    description: 'Practical and stylish Audi A4 Avant with Quattro all-wheel drive. Perfect family car.',
    images: ['https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&q=80', 'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?w=800&q=80'],
    isFeatured: true,
    status: 'available',
  },
  {
    title: 'Volkswagen Golf GTI',
    brand: 'Volkswagen',
    model: 'Golf GTI',
    year: 2022,
    price: 35900,
    mileage: 18000,
    fuelType: 'petrol',
    transmission: 'automatic',
    bodyType: 'hatchback',
    condition: 'used',
    colorExterior: 'Tornado Red',
    colorInterior: 'Tartan',
    powerHP: 245,
    engine: '2.0 TSI',
    drivetrain: 'fwd',
    seats: 5,
    doors: 5,
    features: ['Performance Package', 'DCC Suspension', 'Harman Kardon', 'Digital Cockpit', 'Keyless Entry'],
    description: 'Iconic hot hatch with incredible performance and everyday practicality. A true drivers car.',
    images: ['https://images.unsplash.com/photo-1619682817481-e994891cd1f5?w=800&q=80', 'https://images.unsplash.com/photo-1471479917193-f00955256257?w=800&q=80'],
    isFeatured: true,
    status: 'available',
  },
  {
    title: 'Porsche Cayenne S',
    brand: 'Porsche',
    model: 'Cayenne S',
    year: 2021,
    price: 89500,
    mileage: 32000,
    fuelType: 'petrol',
    transmission: 'automatic',
    bodyType: 'suv',
    condition: 'used',
    colorExterior: 'Carrara White',
    colorInterior: 'Espresso',
    powerHP: 440,
    engine: '2.9L V6 Twin-Turbo',
    drivetrain: 'awd',
    seats: 5,
    doors: 5,
    features: ['Sport Chrono', 'Air Suspension', 'Bose Sound', 'Panoramic Roof', 'PASM'],
    description: 'Powerful and luxurious Porsche Cayenne S. Sports car performance in SUV form.',
    images: ['https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?w=800&q=80', 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&q=80'],
    isFeatured: true,
    status: 'available',
  },
  {
    title: 'Tesla Model 3 Long Range',
    brand: 'Tesla',
    model: 'Model 3',
    year: 2023,
    price: 52000,
    mileage: 8000,
    fuelType: 'electric',
    transmission: 'automatic',
    bodyType: 'sedan',
    condition: 'used',
    colorExterior: 'Pearl White',
    colorInterior: 'White',
    powerHP: 366,
    engine: 'Dual Motor AWD',
    drivetrain: 'awd',
    seats: 5,
    doors: 4,
    features: ['Autopilot', 'Premium Interior', 'Glass Roof', '15" Touchscreen', 'Supercharger Access'],
    description: 'Nearly new Tesla Model 3 with full self-driving capability. The future of driving is here.',
    images: ['https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800&q=80', 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&q=80'],
    isFeatured: true,
    status: 'available',
  },
  {
    title: 'Range Rover Sport HSE',
    brand: 'Land Rover',
    model: 'Range Rover Sport',
    year: 2020,
    price: 68500,
    mileage: 45000,
    fuelType: 'diesel',
    transmission: 'automatic',
    bodyType: 'suv',
    condition: 'used',
    colorExterior: 'Santorini Black',
    colorInterior: 'Ebony',
    powerHP: 306,
    engine: '3.0 SDV6',
    drivetrain: 'awd',
    seats: 5,
    doors: 5,
    features: ['Terrain Response 2', 'Meridian Sound', 'Air Suspension', 'Panoramic Roof', 'Heated/Cooled Seats'],
    description: 'Commanding presence and go-anywhere capability. The ultimate luxury SUV.',
    images: ['https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?w=800&q=80', 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800&q=80'],
    isFeatured: false,
    status: 'available',
  },
  {
    title: 'Toyota RAV4 Hybrid',
    brand: 'Toyota',
    model: 'RAV4',
    year: 2022,
    price: 38900,
    mileage: 25000,
    fuelType: 'hybrid',
    transmission: 'automatic',
    bodyType: 'suv',
    condition: 'used',
    colorExterior: 'Silver',
    colorInterior: 'Black',
    powerHP: 222,
    engine: '2.5L Hybrid',
    drivetrain: 'awd',
    seats: 5,
    doors: 5,
    features: ['Toyota Safety Sense', 'JBL Audio', 'Wireless Charging', 'Heated Seats', 'LED Lights'],
    description: 'Reliable and efficient hybrid SUV from Toyota. Low running costs and great build quality.',
    images: ['https://images.unsplash.com/photo-1594502184342-2e12f877aa73?w=800&q=80', 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800&q=80'],
    isFeatured: false,
    status: 'available',
  },
  {
    title: 'Ford Mustang GT',
    brand: 'Ford',
    model: 'Mustang GT',
    year: 2021,
    price: 55000,
    mileage: 15000,
    fuelType: 'petrol',
    transmission: 'manual',
    bodyType: 'coupe',
    condition: 'used',
    colorExterior: 'Race Red',
    colorInterior: 'Ebony',
    powerHP: 450,
    engine: '5.0L V8',
    drivetrain: 'rwd',
    seats: 4,
    doors: 2,
    features: ['Performance Package', 'MagneRide', 'Recaro Seats', 'Active Exhaust', 'Track Apps'],
    description: 'Iconic American muscle with the legendary 5.0L V8. Pure driving excitement.',
    images: ['https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80', 'https://images.unsplash.com/photo-1621135802920-133df287f89c?w=800&q=80'],
    isFeatured: false,
    status: 'available',
  },
  {
    title: 'Volvo XC60 Recharge',
    brand: 'Volvo',
    model: 'XC60',
    year: 2022,
    price: 58500,
    mileage: 20000,
    fuelType: 'hybrid',
    transmission: 'automatic',
    bodyType: 'suv',
    condition: 'used',
    colorExterior: 'Crystal White',
    colorInterior: 'Charcoal',
    powerHP: 455,
    engine: '2.0L PHEV',
    drivetrain: 'awd',
    seats: 5,
    doors: 5,
    features: ['Pilot Assist', 'Bowers & Wilkins', 'Air Purifier', '360 Camera', 'Heated Steering'],
    description: 'Scandinavian luxury meets plug-in hybrid technology. Safe, stylish, and sustainable.',
    images: ['https://images.unsplash.com/photo-1619682817481-e994891cd1f5?w=800&q=80', 'https://images.unsplash.com/photo-1579091337137-3da292da7bc0?w=800&q=80'],
    isFeatured: false,
    status: 'available',
  },
  {
    title: 'Mazda MX-5 RF',
    brand: 'Mazda',
    model: 'MX-5 RF',
    year: 2021,
    price: 32500,
    mileage: 12000,
    fuelType: 'petrol',
    transmission: 'manual',
    bodyType: 'convertible',
    condition: 'used',
    colorExterior: 'Soul Red',
    colorInterior: 'Tan',
    powerHP: 184,
    engine: '2.0L Skyactiv',
    drivetrain: 'rwd',
    seats: 2,
    doors: 2,
    features: ['Retractable Fastback', 'Bose Sound', 'Leather Seats', 'Bilstein Dampers', 'Limited Slip Diff'],
    description: 'Pure driving joy in a beautifully designed package. The perfect weekend car.',
    images: ['https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80', 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80'],
    isFeatured: false,
    status: 'available',
  },
  {
    title: 'Skoda Octavia RS',
    brand: 'Skoda',
    model: 'Octavia RS',
    year: 2022,
    price: 39900,
    mileage: 28000,
    fuelType: 'petrol',
    transmission: 'automatic',
    bodyType: 'wagon',
    condition: 'used',
    colorExterior: 'Steel Grey',
    colorInterior: 'Black/Red',
    powerHP: 245,
    engine: '2.0 TSI',
    drivetrain: 'fwd',
    seats: 5,
    doors: 5,
    features: ['RS Package', 'Dynamic Chassis', 'Virtual Cockpit', 'Canton Sound', 'Adaptive Cruise'],
    description: 'The practical performance car. Massive boot space with hot hatch performance.',
    images: ['https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&q=80', 'https://images.unsplash.com/photo-1471479917193-f00955256257?w=800&q=80'],
    isFeatured: false,
    status: 'available',
  },
]

export async function POST() {
  try {
    // Check if data exists
    const existingCount = await prisma.car.count()
    if (existingCount > 0) {
      return NextResponse.json({ message: 'Database already seeded', count: existingCount })
    }

    // Seed cars
    for (const carData of sampleCars) {
      const shortId = generateShortId()
      const slug = generateSlug(carData.brand, carData.model, carData.year, carData.title)

      await prisma.car.create({
        data: {
          ...carData,
          shortId,
          slug,
        },
      })
    }

    return NextResponse.json({ message: 'Database seeded successfully', count: sampleCars.length })
  } catch (error) {
    console.error('Seed error:', error)
    return NextResponse.json({ error: 'Failed to seed database' }, { status: 500 })
  }
}
